player:
  name: John Doe
  balance:
    cash: 10.33
    bonus: 3.19

lobby:
  brandName: tain
  gameLaunchUrlTemplate: https://casinotesteur.tain.com/lobby/cwl/igame?gameId={game.id}
  gameIconsUrlTemplate: https://cdn.tain.com/casino/v3/content/flash/online_lobby/tain/icons/id_{game.id}.jpg
  logoUrlTemplate: https://cdn.tain.com/shared/content/backoffice/logo/{config.brandName}_logo.png
  lobbyCategories:
    -
      id: slots
      displayName: Slots
    -
      id: video_pokers
      displayName: Video Poker
    -
      id: table_games
      displayName: Table Games

dictionary:
  games:
    -
      id: 1
      lobbyName: Hunting Season
      devices:
        - mobile
        - desktop
      categories:
        - slots
